package JSON_Money_Maker.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BillsList = 0;
  public static final int Brackets = 1;
  public static final int CoinsList = 2;
  public static final int CountriesList = 3;
  public static final int CreatorName = 4;
  public static final int CurrencySymbol = 5;
  public static final int Data = 6;
  public static final int DataList = 7;
  public static final int Document = 8;
  public static final int MoneyName = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x710461f793be4cd2L, 0xa43edef6a6c682b1L);
    builder.put(0x668849c5ce9eafb8L, BillsList);
    builder.put(0x668849c5ce9dc773L, Brackets);
    builder.put(0x668849c5ce9eafb9L, CoinsList);
    builder.put(0x668849c5ce9eafbbL, CountriesList);
    builder.put(0x668849c5ce9eafb7L, CreatorName);
    builder.put(0x668849c5ce9eafbcL, CurrencySymbol);
    builder.put(0x668849c5ce9eafc4L, Data);
    builder.put(0x668849c5ce9eafbaL, DataList);
    builder.put(0x668849c5ce9dc774L, Document);
    builder.put(0x668849c5ce9eafbeL, MoneyName);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
