package JSON_Money_Maker.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBillsList = createDescriptorForBillsList();
  /*package*/ final ConceptDescriptor myConceptBrackets = createDescriptorForBrackets();
  /*package*/ final ConceptDescriptor myConceptCoinsList = createDescriptorForCoinsList();
  /*package*/ final ConceptDescriptor myConceptCountriesList = createDescriptorForCountriesList();
  /*package*/ final ConceptDescriptor myConceptCreatorName = createDescriptorForCreatorName();
  /*package*/ final ConceptDescriptor myConceptCurrencySymbol = createDescriptorForCurrencySymbol();
  /*package*/ final ConceptDescriptor myConceptData = createDescriptorForData();
  /*package*/ final ConceptDescriptor myConceptDataList = createDescriptorForDataList();
  /*package*/ final ConceptDescriptor myConceptDocument = createDescriptorForDocument();
  /*package*/ final ConceptDescriptor myConceptMoneyName = createDescriptorForMoneyName();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBillsList, myConceptBrackets, myConceptCoinsList, myConceptCountriesList, myConceptCreatorName, myConceptCurrencySymbol, myConceptData, myConceptDataList, myConceptDocument, myConceptMoneyName);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BillsList:
        return myConceptBillsList;
      case LanguageConceptSwitch.Brackets:
        return myConceptBrackets;
      case LanguageConceptSwitch.CoinsList:
        return myConceptCoinsList;
      case LanguageConceptSwitch.CountriesList:
        return myConceptCountriesList;
      case LanguageConceptSwitch.CreatorName:
        return myConceptCreatorName;
      case LanguageConceptSwitch.CurrencySymbol:
        return myConceptCurrencySymbol;
      case LanguageConceptSwitch.Data:
        return myConceptData;
      case LanguageConceptSwitch.DataList:
        return myConceptDataList;
      case LanguageConceptSwitch.Document:
        return myConceptDocument;
      case LanguageConceptSwitch.MoneyName:
        return myConceptMoneyName;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBillsList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "BillsList", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb8L);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189816");
    b.version(3);
    b.aggregate("BillsList", 0x668849c5ce9eafd5L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbaL).optional(false).ordered(true).multiple(false).origin("7388236302625189845").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBrackets() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "Brackets", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9dc773L);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625130355");
    b.version(3);
    b.aggregate("moneyName", 0x668849c5ce9eafc9L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbeL).optional(false).ordered(true).multiple(false).origin("7388236302625189833").done();
    b.aggregate("creator", 0x668849c5ce9eafcaL).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb7L).optional(false).ordered(true).multiple(false).origin("7388236302625189834").done();
    b.aggregate("currencies_symbol", 0x668849c5ce9fdce8L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbcL).optional(false).ordered(true).multiple(false).origin("7388236302625266920").done();
    b.aggregate("countries_availability", 0x668849c5ce9fd9ecL).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbbL).optional(false).ordered(true).multiple(false).origin("7388236302625266156").done();
    b.aggregate("coins_denominations", 0x668849c5ce9ff629L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb9L).optional(false).ordered(true).multiple(false).origin("7388236302625273385").done();
    b.aggregate("bills_denominations", 0x668849c5ce9ffaa3L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb8L).optional(false).ordered(true).multiple(false).origin("7388236302625274531").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCoinsList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "CoinsList", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb9L);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189817");
    b.version(3);
    b.aggregate("CoinsList", 0x668849c5ce9eafd6L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbaL).optional(false).ordered(true).multiple(false).origin("7388236302625189846").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCountriesList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "CountriesList", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbbL);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189819");
    b.version(3);
    b.aggregate("CountriesList", 0x668849c5ce9eafd7L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbaL).optional(false).ordered(true).multiple(false).origin("7388236302625189847").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCreatorName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "CreatorName", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafb7L);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189815");
    b.version(3);
    b.aggregate("DATA", 0x668849c5ce9eafccL).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafc4L).optional(false).ordered(true).multiple(false).origin("7388236302625189836").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCurrencySymbol() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "CurrencySymbol", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbcL);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189820");
    b.version(3);
    b.aggregate("DATA", 0x668849c5ce9eafcdL).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafc4L).optional(false).ordered(true).multiple(false).origin("7388236302625189837").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForData() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "Data", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafc4L);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189828");
    b.version(3);
    b.property("TEXT", 0x668849c5ce9eafc5L).type(PrimitiveTypeId.STRING).origin("7388236302625189829").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "DataList", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbaL);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189818");
    b.version(3);
    b.aggregate("DataList", 0x668849c5ce9eafd4L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafc4L).optional(false).ordered(true).multiple(true).origin("7388236302625189844").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "Document", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9dc774L);
    b.class_(false, false, true);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625130356");
    b.version(3);
    b.aggregate("Brackets", 0x668849c5ce9eafd8L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9dc773L).optional(false).ordered(true).multiple(false).origin("7388236302625189848").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoneyName() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("JSON_Money_Maker", "MoneyName", 0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafbeL);
    b.class_(false, false, false);
    b.origin("r:e4b2ae65-313f-4fdc-9fa1-5816e9a9d422(JSON_Money_Maker.structure)/7388236302625189822");
    b.version(3);
    b.aggregate("DATA", 0x668849c5ce9eafc7L).target(0x710461f793be4cd2L, 0xa43edef6a6c682b1L, 0x668849c5ce9eafc4L).optional(false).ordered(true).multiple(false).origin("7388236302625189831").done();
    return b.create();
  }
}
